// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActions = `-- name: CountActions :one
SELECT COUNT(*) FROM actions WHERE deleted_at IS NULL
`

func (q *Queries) CountActions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAction = `-- name: DeleteAction :one
UPDATE actions
SET deleted_at = NOW(), deleted_user_id = $2
WHERE action_id = $1 AND deleted_at IS NULL
RETURNING action_id
`

type DeleteActionParams struct {
	ActionID      uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteAction(ctx context.Context, arg DeleteActionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAction, arg.ActionID, arg.DeletedUserID)
	var action_id uuid.UUID
	err := row.Scan(&action_id)
	return action_id, err
}

const getAction = `-- name: GetAction :one
SELECT action_id, resource_id, name, description, request_type, url, method, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM actions
WHERE action_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAction(ctx context.Context, actionID uuid.UUID) (*Action, error) {
	row := q.db.QueryRow(ctx, getAction, actionID)
	var i Action
	err := row.Scan(
		&i.ActionID,
		&i.ResourceID,
		&i.Name,
		&i.Description,
		&i.RequestType,
		&i.Url,
		&i.Method,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertAction = `-- name: InsertAction :one
INSERT INTO actions (resource_id, name, description, request_type, url, method, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING action_id, resource_id, name, description, request_type, url, method, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertActionParams struct {
	ResourceID    uuid.UUID
	Name          string
	Description   pgtype.Text
	RequestType   RequestType
	Url           string
	Method        string
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (*Action, error) {
	row := q.db.QueryRow(ctx, insertAction,
		arg.ResourceID,
		arg.Name,
		arg.Description,
		arg.RequestType,
		arg.Url,
		arg.Method,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Action
	err := row.Scan(
		&i.ActionID,
		&i.ResourceID,
		&i.Name,
		&i.Description,
		&i.RequestType,
		&i.Url,
		&i.Method,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listActions = `-- name: ListActions :many
SELECT action_id, resource_id, name, description, request_type, url, method, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM actions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListActions(ctx context.Context, arg ListActionsParams) ([]*Action, error) {
	rows, err := q.db.Query(ctx, listActions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ActionID,
			&i.ResourceID,
			&i.Name,
			&i.Description,
			&i.RequestType,
			&i.Url,
			&i.Method,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsByResource = `-- name: ListActionsByResource :many
SELECT action_id, resource_id, name, description, request_type, url, method, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM actions
WHERE resource_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActionsByResourceParams struct {
	ResourceID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListActionsByResource(ctx context.Context, arg ListActionsByResourceParams) ([]*Action, error) {
	rows, err := q.db.Query(ctx, listActionsByResource, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ActionID,
			&i.ResourceID,
			&i.Name,
			&i.Description,
			&i.RequestType,
			&i.Url,
			&i.Method,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAction = `-- name: UpdateAction :one
UPDATE actions
SET resource_id = $2, name = $3, description = $4, request_type = $5, url = $6, method = $7, updated_at = NOW(), updated_user_id = $8
WHERE action_id = $1 AND deleted_at IS NULL
RETURNING action_id, resource_id, name, description, request_type, url, method, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateActionParams struct {
	ActionID      uuid.UUID
	ResourceID    uuid.UUID
	Name          string
	Description   pgtype.Text
	RequestType   RequestType
	Url           string
	Method        string
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateAction(ctx context.Context, arg UpdateActionParams) (*Action, error) {
	row := q.db.QueryRow(ctx, updateAction,
		arg.ActionID,
		arg.ResourceID,
		arg.Name,
		arg.Description,
		arg.RequestType,
		arg.Url,
		arg.Method,
		arg.UpdatedUserID,
	)
	var i Action
	err := row.Scan(
		&i.ActionID,
		&i.ResourceID,
		&i.Name,
		&i.Description,
		&i.RequestType,
		&i.Url,
		&i.Method,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
