// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RequestType string

const (
	RequestTypeVIEW      RequestType = "VIEW"
	RequestTypeHTTP      RequestType = "HTTP"
	RequestTypeGRAPHQL   RequestType = "GRAPHQL"
	RequestTypeGRPC      RequestType = "GRPC"
	RequestTypeWEBSOCKET RequestType = "WEBSOCKET"
)

func (e *RequestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestType(s)
	case string:
		*e = RequestType(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestType: %T", src)
	}
	return nil
}

type NullRequestType struct {
	RequestType RequestType
	Valid       bool // Valid is true if RequestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestType) Scan(value interface{}) error {
	if value == nil {
		ns.RequestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestType), nil
}

type UserStatus string

const (
	UserStatusACTIVE      UserStatus = "ACTIVE"
	UserStatusDEACTIVATED UserStatus = "DEACTIVATED"
	UserStatusDELETED     UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Action struct {
	ActionID      uuid.UUID
	ResourceID    uuid.UUID
	Name          string
	Description   pgtype.Text
	RequestType   RequestType
	Url           string
	Method        string
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type Module struct {
	ModuleID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Url           pgtype.Text
	Icon          pgtype.Text
	ProductID     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type OnlineUser struct {
	OnlineUserID   uuid.UUID
	UserID         uuid.UUID
	SocketID       string
	DeviceInfo     pgtype.Text
	CurrentPageUrl pgtype.Text
	CreatedAt      pgtype.Timestamptz
	CreatedUserID  pgtype.Text
	UpdatedAt      pgtype.Timestamptz
	UpdatedUserID  pgtype.Text
	DeletedAt      pgtype.Timestamptz
	DeletedUserID  pgtype.Text
}

type Permission struct {
	PermissionID  uuid.UUID
	RoleID        uuid.UUID
	ResourceID    uuid.UUID
	ActionID      uuid.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type Product struct {
	ProductID     uuid.UUID
	Name          string
	Description   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
	Url           pgtype.Text
}

type Resource struct {
	ResourceID    uuid.UUID
	Name          string
	ModuleID      uuid.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type Role struct {
	RoleID        uuid.UUID
	Name          string
	Description   pgtype.Text
	ModuleID      uuid.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type User struct {
	UserID        uuid.UUID
	UserName      string
	Email         string
	Password      string
	Phone         pgtype.Text
	Avatar        pgtype.Text
	Status        UserStatus
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}

type UserRole struct {
	UserRoleID    uuid.UUID
	UserID        uuid.UUID
	RoleID        uuid.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedUserID pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	UpdatedUserID pgtype.Text
	DeletedAt     pgtype.Timestamptz
	DeletedUserID pgtype.Text
}
