// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countModules = `-- name: CountModules :one
SELECT COUNT(*) FROM modules WHERE deleted_at IS NULL
`

func (q *Queries) CountModules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countModules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteModule = `-- name: DeleteModule :one
UPDATE modules
SET deleted_at = NOW(), deleted_user_id = $2
WHERE module_id = $1 AND deleted_at IS NULL
RETURNING module_id
`

type DeleteModuleParams struct {
	ModuleID      uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteModule(ctx context.Context, arg DeleteModuleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteModule, arg.ModuleID, arg.DeletedUserID)
	var module_id uuid.UUID
	err := row.Scan(&module_id)
	return module_id, err
}

const getModule = `-- name: GetModule :one
SELECT module_id, name, description, url, icon, product_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM modules
WHERE module_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetModule(ctx context.Context, moduleID uuid.UUID) (*Module, error) {
	row := q.db.QueryRow(ctx, getModule, moduleID)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Icon,
		&i.ProductID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertModule = `-- name: InsertModule :one
INSERT INTO modules (name, description, url, icon, product_id, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING module_id, name, description, url, icon, product_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertModuleParams struct {
	Name          string
	Description   pgtype.Text
	Url           pgtype.Text
	Icon          pgtype.Text
	ProductID     pgtype.UUID
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertModule(ctx context.Context, arg InsertModuleParams) (*Module, error) {
	row := q.db.QueryRow(ctx, insertModule,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Icon,
		arg.ProductID,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Icon,
		&i.ProductID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listModules = `-- name: ListModules :many
SELECT module_id, name, description, url, icon, product_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM modules
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListModulesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListModules(ctx context.Context, arg ListModulesParams) ([]*Module, error) {
	rows, err := q.db.Query(ctx, listModules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ModuleID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Icon,
			&i.ProductID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET name = $2, description = $3, url = $4, icon = $5, product_id = $6, updated_at = NOW(), updated_user_id = $7
WHERE module_id = $1 AND deleted_at IS NULL
RETURNING module_id, name, description, url, icon, product_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateModuleParams struct {
	ModuleID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Url           pgtype.Text
	Icon          pgtype.Text
	ProductID     pgtype.UUID
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (*Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ModuleID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Icon,
		arg.ProductID,
		arg.UpdatedUserID,
	)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Icon,
		&i.ProductID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
