// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: online_users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOnlineUsersByUser = `-- name: CountOnlineUsersByUser :one
SELECT COUNT(*) FROM online_users WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountOnlineUsersByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOnlineUsersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOnlineUser = `-- name: DeleteOnlineUser :one
UPDATE online_users
SET deleted_at = NOW(), deleted_user_id = $2
WHERE online_user_id = $1 AND deleted_at IS NULL
RETURNING online_user_id
`

type DeleteOnlineUserParams struct {
	OnlineUserID  uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteOnlineUser(ctx context.Context, arg DeleteOnlineUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteOnlineUser, arg.OnlineUserID, arg.DeletedUserID)
	var online_user_id uuid.UUID
	err := row.Scan(&online_user_id)
	return online_user_id, err
}

const deleteOnlineUserBySocket = `-- name: DeleteOnlineUserBySocket :exec
DELETE FROM online_users WHERE user_id = $1 AND socket_id = $2
`

type DeleteOnlineUserBySocketParams struct {
	UserID   uuid.UUID
	SocketID string
}

func (q *Queries) DeleteOnlineUserBySocket(ctx context.Context, arg DeleteOnlineUserBySocketParams) error {
	_, err := q.db.Exec(ctx, deleteOnlineUserBySocket, arg.UserID, arg.SocketID)
	return err
}

const getOnlineUser = `-- name: GetOnlineUser :one
SELECT online_user_id, user_id, socket_id, device_info, current_page_url, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM online_users
WHERE online_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOnlineUser(ctx context.Context, onlineUserID uuid.UUID) (*OnlineUser, error) {
	row := q.db.QueryRow(ctx, getOnlineUser, onlineUserID)
	var i OnlineUser
	err := row.Scan(
		&i.OnlineUserID,
		&i.UserID,
		&i.SocketID,
		&i.DeviceInfo,
		&i.CurrentPageUrl,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertOnlineUser = `-- name: InsertOnlineUser :one
INSERT INTO online_users (user_id, socket_id, device_info, current_page_url, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING online_user_id, user_id, socket_id, device_info, current_page_url, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertOnlineUserParams struct {
	UserID         uuid.UUID
	SocketID       string
	DeviceInfo     pgtype.Text
	CurrentPageUrl pgtype.Text
	CreatedUserID  pgtype.Text
	UpdatedUserID  pgtype.Text
}

func (q *Queries) InsertOnlineUser(ctx context.Context, arg InsertOnlineUserParams) (*OnlineUser, error) {
	row := q.db.QueryRow(ctx, insertOnlineUser,
		arg.UserID,
		arg.SocketID,
		arg.DeviceInfo,
		arg.CurrentPageUrl,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i OnlineUser
	err := row.Scan(
		&i.OnlineUserID,
		&i.UserID,
		&i.SocketID,
		&i.DeviceInfo,
		&i.CurrentPageUrl,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listOnlineUsersByUser = `-- name: ListOnlineUsersByUser :many
SELECT online_user_id, user_id, socket_id, device_info, current_page_url, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM online_users
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOnlineUsersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListOnlineUsersByUser(ctx context.Context, arg ListOnlineUsersByUserParams) ([]*OnlineUser, error) {
	rows, err := q.db.Query(ctx, listOnlineUsersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OnlineUser
	for rows.Next() {
		var i OnlineUser
		if err := rows.Scan(
			&i.OnlineUserID,
			&i.UserID,
			&i.SocketID,
			&i.DeviceInfo,
			&i.CurrentPageUrl,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
