// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermissions = `-- name: CountPermissions :one
SELECT COUNT(*) FROM permissions WHERE deleted_at IS NULL
`

func (q *Queries) CountPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePermission = `-- name: DeletePermission :one
UPDATE permissions
SET deleted_at = NOW(), deleted_user_id = $2
WHERE permission_id = $1 AND deleted_at IS NULL
RETURNING permission_id
`

type DeletePermissionParams struct {
	PermissionID  uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deletePermission, arg.PermissionID, arg.DeletedUserID)
	var permission_id uuid.UUID
	err := row.Scan(&permission_id)
	return permission_id, err
}

const getPermission = `-- name: GetPermission :one
SELECT permission_id, role_id, resource_id, action_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM permissions
WHERE permission_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPermission(ctx context.Context, permissionID uuid.UUID) (*Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, permissionID)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.RoleID,
		&i.ResourceID,
		&i.ActionID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertPermission = `-- name: InsertPermission :one
INSERT INTO permissions (role_id, resource_id, action_id, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING permission_id, role_id, resource_id, action_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertPermissionParams struct {
	RoleID        uuid.UUID
	ResourceID    uuid.UUID
	ActionID      uuid.UUID
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) (*Permission, error) {
	row := q.db.QueryRow(ctx, insertPermission,
		arg.RoleID,
		arg.ResourceID,
		arg.ActionID,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.RoleID,
		&i.ResourceID,
		&i.ActionID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT permission_id, role_id, resource_id, action_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM permissions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]*Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.PermissionID,
			&i.RoleID,
			&i.ResourceID,
			&i.ActionID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT permission_id, role_id, resource_id, action_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM permissions
WHERE role_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPermissionsByRoleParams struct {
	RoleID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListPermissionsByRole(ctx context.Context, arg ListPermissionsByRoleParams) ([]*Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRole, arg.RoleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.PermissionID,
			&i.RoleID,
			&i.ResourceID,
			&i.ActionID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET role_id = $2, resource_id = $3, action_id = $4, updated_at = NOW(), updated_user_id = $5
WHERE permission_id = $1 AND deleted_at IS NULL
RETURNING permission_id, role_id, resource_id, action_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdatePermissionParams struct {
	PermissionID  uuid.UUID
	RoleID        uuid.UUID
	ResourceID    uuid.UUID
	ActionID      uuid.UUID
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (*Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.PermissionID,
		arg.RoleID,
		arg.ResourceID,
		arg.ActionID,
		arg.UpdatedUserID,
	)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.RoleID,
		&i.ResourceID,
		&i.ActionID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
