// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)
FROM products
WHERE
	deleted_at IS NULL
	AND ($1::VARCHAR = '' OR name ILIKE CONCAT('%', $1::VARCHAR, '%'))
	AND ($2::VARCHAR = '' OR description ILIKE CONCAT('%', $2::VARCHAR, '%'))
	AND (COALESCE(array_length($3::UUID[], 1), 0) = 0 OR product_id = ANY($3::UUID[]))
`

type CountProductsParams struct {
	Name        string
	Description string
	ProductIds  []uuid.UUID
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Name, arg.Description, arg.ProductIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProduct = `-- name: DeleteProduct :one
UPDATE products
SET deleted_at = NOW(), deleted_user_id = $2
WHERE product_id = $1 AND deleted_at IS NULL
RETURNING product_id
`

type DeleteProductParams struct {
	ProductID     uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProduct, arg.ProductID, arg.DeletedUserID)
	var product_id uuid.UUID
	err := row.Scan(&product_id)
	return product_id, err
}

const getProduct = `-- name: GetProduct :one
SELECT product_id, name, description, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id, url
FROM products
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, productID uuid.UUID) (*Product, error) {
	row := q.db.QueryRow(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
		&i.Url,
	)
	return &i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (name, description, url, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING product_id, name, description, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id, url
`

type InsertProductParams struct {
	Name          string
	Description   pgtype.Text
	Url           pgtype.Text
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
		&i.Url,
	)
	return &i, err
}

const listProducts = `-- name: ListProducts :many
SELECT product_id, name, description, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id, url
FROM products
WHERE
	deleted_at IS NULL
	AND ($1::VARCHAR = '' OR name ILIKE CONCAT('%', $1::VARCHAR, '%'))
	AND ($2::VARCHAR = '' OR description ILIKE CONCAT('%', $2::VARCHAR, '%'))
	AND (COALESCE(array_length($3::UUID[], 1), 0) = 0 OR product_id = ANY($3::UUID[]))
ORDER BY
	CASE WHEN $4::TEXT = 'product_id' AND $5::TEXT = 'ASC' THEN product_id END ASC,
	CASE WHEN $4::TEXT = 'product_id' AND $5::TEXT = 'DESC' THEN product_id END DESC,
	CASE WHEN $4::TEXT = 'name' AND $5::TEXT = 'ASC' THEN name END ASC,
	CASE WHEN $4::TEXT = 'name' AND $5::TEXT = 'DESC' THEN name END DESC,
	CASE WHEN $4::TEXT = 'created_at' AND $5::TEXT = 'ASC' THEN created_at END ASC,
	CASE WHEN $4::TEXT = 'created_at' AND $5::TEXT = 'DESC' THEN created_at END DESC,
	CASE WHEN $4::TEXT = 'updated_at' AND $5::TEXT = 'ASC' THEN updated_at END ASC,
	CASE WHEN $4::TEXT = 'updated_at' AND $5::TEXT = 'DESC' THEN updated_at END DESC,

	CASE WHEN $6::TEXT = 'product_id' AND $7::TEXT = 'ASC' THEN product_id END ASC,
	CASE WHEN $6::TEXT = 'product_id' AND $7::TEXT = 'DESC' THEN product_id END DESC,
	CASE WHEN $6::TEXT = 'name' AND $7::TEXT = 'ASC' THEN name END ASC,
	CASE WHEN $6::TEXT = 'name' AND $7::TEXT = 'DESC' THEN name END DESC,
	CASE WHEN $6::TEXT = 'created_at' AND $7::TEXT = 'ASC' THEN created_at END ASC,
	CASE WHEN $6::TEXT = 'created_at' AND $7::TEXT = 'DESC' THEN created_at END DESC,
	CASE WHEN $6::TEXT = 'updated_at' AND $7::TEXT = 'ASC' THEN updated_at END ASC,
	CASE WHEN $6::TEXT = 'updated_at' AND $7::TEXT = 'DESC' THEN updated_at END DESC,

	CASE WHEN $8::TEXT = 'product_id' AND $9::TEXT = 'ASC' THEN product_id END ASC,
	CASE WHEN $8::TEXT = 'product_id' AND $9::TEXT = 'DESC' THEN product_id END DESC,
	CASE WHEN $8::TEXT = 'name' AND $9::TEXT = 'ASC' THEN name END ASC,
	CASE WHEN $8::TEXT = 'name' AND $9::TEXT = 'DESC' THEN name END DESC,
	CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'ASC' THEN created_at END ASC,
	CASE WHEN $8::TEXT = 'created_at' AND $9::TEXT = 'DESC' THEN created_at END DESC,
	CASE WHEN $8::TEXT = 'updated_at' AND $9::TEXT = 'ASC' THEN updated_at END ASC,
	CASE WHEN $8::TEXT = 'updated_at' AND $9::TEXT = 'DESC' THEN updated_at END DESC,
	CASE WHEN $8::TEXT = 'url' AND $9::TEXT = 'ASC' THEN url END ASC,
	CASE WHEN $8::TEXT = 'url' AND $9::TEXT = 'DESC' THEN url END DESC,
	created_at DESC
LIMIT $11 OFFSET $10
`

type ListProductsParams struct {
	Name        string
	Description string
	ProductIds  []uuid.UUID
	SortField1  string
	SortOrder1  string
	SortField2  string
	SortOrder2  string
	SortField3  string
	SortOrder3  string
	POffset     int32
	PLimit      int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]*Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Name,
		arg.Description,
		arg.ProductIds,
		arg.SortField1,
		arg.SortOrder1,
		arg.SortField2,
		arg.SortOrder2,
		arg.SortField3,
		arg.SortOrder3,
		arg.POffset,
		arg.PLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, url = $4, updated_at = NOW(), updated_user_id = $5
WHERE product_id = $1 AND deleted_at IS NULL
RETURNING product_id, name, description, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id, url
`

type UpdateProductParams struct {
	ProductID     uuid.UUID
	Name          string
	Description   pgtype.Text
	Url           pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.UpdatedUserID,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
		&i.Url,
	)
	return &i, err
}
