// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources WHERE deleted_at IS NULL
`

func (q *Queries) CountResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteResource = `-- name: DeleteResource :one
UPDATE resources
SET deleted_at = NOW(), deleted_user_id = $2
WHERE resource_id = $1 AND deleted_at IS NULL
RETURNING resource_id
`

type DeleteResourceParams struct {
	ResourceID    uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteResource, arg.ResourceID, arg.DeletedUserID)
	var resource_id uuid.UUID
	err := row.Scan(&resource_id)
	return resource_id, err
}

const getResource = `-- name: GetResource :one
SELECT resource_id, name, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM resources
WHERE resource_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResource(ctx context.Context, resourceID uuid.UUID) (*Resource, error) {
	row := q.db.QueryRow(ctx, getResource, resourceID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.Name,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertResource = `-- name: InsertResource :one
INSERT INTO resources (name, module_id, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4)
RETURNING resource_id, name, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertResourceParams struct {
	Name          string
	ModuleID      uuid.UUID
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) (*Resource, error) {
	row := q.db.QueryRow(ctx, insertResource,
		arg.Name,
		arg.ModuleID,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.Name,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listResources = `-- name: ListResources :many
SELECT resource_id, name, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM resources
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListResourcesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]*Resource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.Name,
			&i.ModuleID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByModule = `-- name: ListResourcesByModule :many
SELECT resource_id, name, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM resources
WHERE module_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByModuleParams struct {
	ModuleID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListResourcesByModule(ctx context.Context, arg ListResourcesByModuleParams) ([]*Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByModule, arg.ModuleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.Name,
			&i.ModuleID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name = $2, module_id = $3, updated_at = NOW(), updated_user_id = $4
WHERE resource_id = $1 AND deleted_at IS NULL
RETURNING resource_id, name, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateResourceParams struct {
	ResourceID    uuid.UUID
	Name          string
	ModuleID      uuid.UUID
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (*Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ResourceID,
		arg.Name,
		arg.ModuleID,
		arg.UpdatedUserID,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.Name,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
