// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM roles WHERE deleted_at IS NULL
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRole = `-- name: DeleteRole :one
UPDATE roles
SET deleted_at = NOW(), deleted_user_id = $2
WHERE role_id = $1 AND deleted_at IS NULL
RETURNING role_id
`

type DeleteRoleParams struct {
	RoleID        uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteRole, arg.RoleID, arg.DeletedUserID)
	var role_id uuid.UUID
	err := row.Scan(&role_id)
	return role_id, err
}

const getRole = `-- name: GetRole :one
SELECT role_id, name, description, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM roles
WHERE role_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRole(ctx context.Context, roleID uuid.UUID) (*Role, error) {
	row := q.db.QueryRow(ctx, getRole, roleID)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, name, description, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM roles
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT role_id FROM roles WHERE role_id = ANY($1::uuid[]) AND deleted_at IS NULL
`

func (q *Queries) GetRolesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (name, description, module_id, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING role_id, name, description, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertRoleParams struct {
	Name          string
	Description   pgtype.Text
	ModuleID      uuid.UUID
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (*Role, error) {
	row := q.db.QueryRow(ctx, insertRole,
		arg.Name,
		arg.Description,
		arg.ModuleID,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listRoles = `-- name: ListRoles :many
SELECT role_id, name, description, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM roles
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRolesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.RoleID,
			&i.Name,
			&i.Description,
			&i.ModuleID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, module_id = $4, updated_at = NOW(), updated_user_id = $5
WHERE role_id = $1 AND deleted_at IS NULL
RETURNING role_id, name, description, module_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateRoleParams struct {
	RoleID        uuid.UUID
	Name          string
	Description   pgtype.Text
	ModuleID      uuid.UUID
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.RoleID,
		arg.Name,
		arg.Description,
		arg.ModuleID,
		arg.UpdatedUserID,
	)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.ModuleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
