// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET deleted_at = NOW(), deleted_user_id = $2
WHERE user_id = $1 AND deleted_at IS NULL
RETURNING user_id
`

type DeleteUserParams struct {
	UserID        uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.UserID, arg.DeletedUserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM users
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, userID uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM users
WHERE user_name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, userName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (user_name, email, password, phone, avatar, status, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertUserParams struct {
	UserName      string
	Email         string
	Password      string
	Phone         pgtype.Text
	Avatar        pgtype.Text
	Status        UserStatus
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Avatar,
		arg.Status,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Avatar,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET user_name = $2, email = $3, password = $4, phone = $5, avatar = $6, status = $7, updated_at = NOW(), updated_user_id = $8
WHERE user_id = $1 AND deleted_at IS NULL
RETURNING user_id, user_name, email, password, phone, avatar, status, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateUserParams struct {
	UserID        uuid.UUID
	UserName      string
	Email         string
	Password      string
	Phone         pgtype.Text
	Avatar        pgtype.Text
	Status        UserStatus
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Avatar,
		arg.Status,
		arg.UpdatedUserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
