// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserRoles = `-- name: CountUserRoles :one
SELECT COUNT(*) FROM user_roles WHERE deleted_at IS NULL
`

func (q *Queries) CountUserRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserRole = `-- name: DeleteUserRole :one
UPDATE user_roles
SET deleted_at = NOW(), deleted_user_id = $2
WHERE user_role_id = $1 AND deleted_at IS NULL
RETURNING user_role_id
`

type DeleteUserRoleParams struct {
	UserRoleID    uuid.UUID
	DeletedUserID pgtype.Text
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUserRole, arg.UserRoleID, arg.DeletedUserID)
	var user_role_id uuid.UUID
	err := row.Scan(&user_role_id)
	return user_role_id, err
}

const deleteUserRoleMappingsByUserID = `-- name: DeleteUserRoleMappingsByUserID :exec
UPDATE user_roles SET deleted_at = NOW() WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUserRoleMappingsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoleMappingsByUserID, userID)
	return err
}

const getUserRole = `-- name: GetUserRole :one
SELECT user_role_id, user_id, role_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM user_roles
WHERE user_role_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserRole(ctx context.Context, userRoleID uuid.UUID) (*UserRole, error) {
	row := q.db.QueryRow(ctx, getUserRole, userRoleID)
	var i UserRole
	err := row.Scan(
		&i.UserRoleID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const insertUserRole = `-- name: InsertUserRole :one
INSERT INTO user_roles (user_id, role_id, created_user_id, updated_user_id)
VALUES ($1, $2, $3, $4)
RETURNING user_role_id, user_id, role_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type InsertUserRoleParams struct {
	UserID        uuid.UUID
	RoleID        uuid.UUID
	CreatedUserID pgtype.Text
	UpdatedUserID pgtype.Text
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) (*UserRole, error) {
	row := q.db.QueryRow(ctx, insertUserRole,
		arg.UserID,
		arg.RoleID,
		arg.CreatedUserID,
		arg.UpdatedUserID,
	)
	var i UserRole
	err := row.Scan(
		&i.UserRoleID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}

const listRolesByUser = `-- name: ListRolesByUser :many
SELECT r.role_id, r.name, r.description, r.module_id, r.created_at, r.created_user_id, r.updated_at, r.updated_user_id, r.deleted_at, r.deleted_user_id
FROM roles r
JOIN user_roles ur ON ur.role_id = r.role_id
WHERE ur.user_id = $1 AND ur.deleted_at IS NULL AND r.deleted_at IS NULL
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRolesByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListRolesByUser(ctx context.Context, arg ListRolesByUserParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRolesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.RoleID,
			&i.Name,
			&i.Description,
			&i.ModuleID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT user_role_id, user_id, role_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
FROM user_roles
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserRolesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]*UserRole, error) {
	rows, err := q.db.Query(ctx, listUserRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.UserRoleID,
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
			&i.CreatedUserID,
			&i.UpdatedAt,
			&i.UpdatedUserID,
			&i.DeletedAt,
			&i.DeletedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE user_roles
SET user_id = $2, role_id = $3, updated_at = NOW(), updated_user_id = $4
WHERE user_role_id = $1 AND deleted_at IS NULL
RETURNING user_role_id, user_id, role_id, created_at, created_user_id, updated_at, updated_user_id, deleted_at, deleted_user_id
`

type UpdateUserRoleParams struct {
	UserRoleID    uuid.UUID
	UserID        uuid.UUID
	RoleID        uuid.UUID
	UpdatedUserID pgtype.Text
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (*UserRole, error) {
	row := q.db.QueryRow(ctx, updateUserRole,
		arg.UserRoleID,
		arg.UserID,
		arg.RoleID,
		arg.UpdatedUserID,
	)
	var i UserRole
	err := row.Scan(
		&i.UserRoleID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedUserID,
		&i.UpdatedAt,
		&i.UpdatedUserID,
		&i.DeletedAt,
		&i.DeletedUserID,
	)
	return &i, err
}
