package test

import (
	"bytes"
	"context"
	"encoding/json"
	"log/slog"
	"net"
	"strings"
	"testing"

	applogger "go-api/internal/logger"

	basev1 "github.com/lamquangmanh/protobuf/gen/go/proto/base/v1"
	userv1 "github.com/lamquangmanh/protobuf/gen/go/proto/user/v1"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
)

func TestUnaryServerInterceptor_LogsGrpcErrorDetails(t *testing.T) {
	// This test ensures transport-level gRPC errors are logged with both
	// canonical status code and human-readable error message for easier tracing.
	//
	// Arrange:
	// - Create a JSON logger writing into an in-memory buffer.
	// - Build interceptor with that logger.
	// - Provide request metadata and peer info to mimic a real call context.
	//
	// Act:
	// - Execute interceptor with a handler that returns gRPC InvalidArgument.
	//
	// Assert:
	// - Interceptor must return the handler error.
	// - Logged JSON entry must include failure message, status code, and error text.
	var logBuffer bytes.Buffer
	logger := slog.New(slog.NewJSONHandler(&logBuffer, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interceptor := applogger.UnaryServerInterceptor(logger)

	ctx := metadata.NewIncomingContext(context.Background(), metadata.Pairs("x-request-id", "req-transport-error"))
	ctx = peer.NewContext(ctx, &peer.Peer{Addr: &net.TCPAddr{IP: net.ParseIP("127.0.0.1"), Port: 39000}})

	_, err := interceptor(ctx, nil, &grpc.UnaryServerInfo{FullMethod: "/go.api.user.v1.UserService/GetUser"}, func(context.Context, any) (any, error) {
		return nil, status.Error(codes.InvalidArgument, "invalid user id format")
	})
	// The original handler error must be propagated to caller.
	if err == nil {
		t.Fatal("expected handler error, got nil")
	}

	// Decode the only JSON log line generated by this call.
	entry := decodeSingleJSONLog(t, logBuffer.Bytes())
	// Verify semantic log message for transport-level failure path.
	if entry["msg"] != "grpc request failed" {
		t.Fatalf("expected failed log message, got %v", entry["msg"])
	}
	// Verify canonical gRPC code is included for easier filtering/alerting.
	if entry["code"] != "InvalidArgument" {
		t.Fatalf("expected code InvalidArgument, got %v", entry["code"])
	}
	// Verify detailed error text is present for quick root-cause lookup.
	errorText, ok := entry["error"].(string)
	if !ok || !strings.Contains(errorText, "invalid user id format") {
		t.Fatalf("expected detailed error text, got %v", entry["error"])
	}
}

func TestUnaryServerInterceptor_LogsAllResponseErrors(t *testing.T) {
	// This test verifies business-level errors returned in response payload
	// (CreateUserResponse.errors) are fully logged, not just a single message.
	//
	// Arrange:
	// - Create buffered JSON logger and interceptor.
	// - Build a handler that returns success at transport level (err=nil)
	//   but includes validation/business errors in response.Errors.
	//
	// Act:
	// - Execute interceptor once.
	//
	// Assert:
	// - Interceptor should keep err=nil.
	// - Log level path should be "completed with response errors".
	// - response_error_count and detailed response_errors should be present.
	var logBuffer bytes.Buffer
	logger := slog.New(slog.NewJSONHandler(&logBuffer, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interceptor := applogger.UnaryServerInterceptor(logger)

	ctx := metadata.NewIncomingContext(context.Background(), metadata.Pairs("x-request-id", "req-response-error"))

	resp, err := interceptor(ctx, nil, &grpc.UnaryServerInfo{FullMethod: "/go.api.user.v1.UserService/CreateUser"}, func(context.Context, any) (any, error) {
		return &userv1.CreateUserResponse{Errors: []*basev1.ErrorMessage{
			{Code: int32(codes.InvalidArgument), Message: "username is required"},
			{Code: int32(codes.AlreadyExists), Message: "email already exists"},
		}}, nil
	})
	// Business errors in payload should not be converted into transport error.
	if err != nil {
		t.Fatalf("expected nil error, got %v", err)
	}
	// Response itself should still be returned to caller.
	if resp == nil {
		t.Fatal("expected non-nil response")
	}

	entry := decodeSingleJSONLog(t, logBuffer.Bytes())
	// Verify dedicated message for response-level errors.
	if entry["msg"] != "grpc request completed with response errors" {
		t.Fatalf("expected response-errors log message, got %v", entry["msg"])
	}
	// Transport status remains OK because err is nil.
	if entry["code"] != "OK" {
		t.Fatalf("expected code OK, got %v", entry["code"])
	}

	// Ensure count matches number of returned ErrorItem objects.
	count, ok := entry["response_error_count"].(float64)
	if !ok || int(count) != 2 {
		t.Fatalf("expected response_error_count 2, got %v", entry["response_error_count"])
	}

	// Ensure full structured error list is logged.
	errorsList, ok := entry["response_errors"].([]any)
	if !ok || len(errorsList) != 2 {
		t.Fatalf("expected 2 response errors, got %v", entry["response_errors"])
	}

	// Validate first object payload fields (code/message) for trace detail.
	first, ok := errorsList[0].(map[string]any)
	if !ok {
		t.Fatalf("expected first response error object, got %T", errorsList[0])
	}
	if first["code"] != float64(codes.InvalidArgument) {
		t.Fatalf("expected first error code %d, got %v", codes.InvalidArgument, first["code"])
	}
	if first["message"] != "username is required" {
		t.Fatalf("expected first error message, got %v", first["message"])
	}
}

func decodeSingleJSONLog(t *testing.T, raw []byte) map[string]any {
	// Mark helper so failure lines point to caller test, not helper internals.
	t.Helper()

	// Interceptor writes one JSON object per invocation; trim for robust parsing.
	line := strings.TrimSpace(string(raw))
	if line == "" {
		t.Fatal("expected log output, got empty buffer")
	}

	// Decode JSON log entry into a generic map for field assertions.
	var entry map[string]any
	if err := json.Unmarshal([]byte(line), &entry); err != nil {
		t.Fatalf("decode log entry: %v; raw=%s", err, line)
	}
	return entry
}
