#!/usr/bin/env bash
# ============================================================
# test_all_apis.sh – smoke-test every gRPC endpoint and dump
# request/response pairs to docs/api_test_results.md
# ============================================================
set -euo pipefail

ADDR="localhost:50051"
OUT="docs/api_test_results.md"

# ---- seed IDs (adjust if DB is wiped) ----------------------
USER_ID="b1aa92ce-fd81-4787-90b9-95f9c3639fce"
PRODUCT_ID="95ec8af3-64be-4b61-a5c9-fbf4b0638d5f"
MODULE_ID="2cce26f5-7266-49cf-b487-84e6fa0e41e1"

mkdir -p docs

# ---- pre-create a resource so Action tests have a valid resource_id ----------
SETUP_RESOURCE_ID=$(grpcurl -plaintext \
    -d '{"resource":{"name":"setup-resource","module_id":"'"2cce26f5-7266-49cf-b487-84e6fa0e41e1"'"},"user_id":"'"b1aa92ce-fd81-4787-90b9-95f9c3639fce"'"}' \
    localhost:50051 proto.resource.v1.ResourceService/CreateResource 2>/dev/null \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('resource',{}).get('resourceId',''))" 2>/dev/null || true)
if [[ -z "${SETUP_RESOURCE_ID}" ]]; then
    SETUP_RESOURCE_ID=$(psql -U postgres -d go_api -t -c "SELECT resource_id FROM resources LIMIT 1;" 2>/dev/null | tr -d ' \n' || true)
fi

# ---- helpers -----------------------------------------------
call() {
    local label="$1"; local svc="$2"; local method="$3"; local payload="$4"
    echo ""
    echo "### ${label}"
    echo ""
    echo '**Request:**'
    echo '```json'
    echo "${payload}" | python3 -m json.tool 2>/dev/null || echo "${payload}"
    echo '```'
    echo ""
    echo '**Response:**'
    echo '```json'
    grpcurl -plaintext -d "${payload}" ${ADDR} "${svc}/${method}" 2>&1 || true
    echo '```'
    echo ""
}

call_empty() {
    local label="$1"; local svc="$2"; local method="$3"
    echo ""
    echo "### ${label}"
    echo ""
    echo '**Request:** *(empty)*'
    echo ""
    echo '**Response:**'
    echo '```json'
    grpcurl -plaintext ${ADDR} "${svc}/${method}" 2>&1 || true
    echo '```'
    echo ""
}

{
cat <<'HEADER'
# API Test Results

> Generated by `scripts/test_all_apis.sh`  
> Server: `localhost:50051` (gRPC, plaintext)

---

## Table of Contents

1. [ProductService](#productservice)
2. [ModuleService](#moduleservice)
3. [ActionService](#actionservice)
4. [ResourceService](#resourceservice)
5. [UserService](#userservice)
6. [RoleService](#roleservice)
7. [AuthService](#authservice)
8. [MenuService](#menuservice)
9. [PermissionService](#permissionservice)

---

## ProductService
HEADER

# ---- PRODUCT -----------------------------------------------
call "GetProducts (page 1, limit 5)" \
    "proto.product.v1.ProductService" "GetProducts" \
    '{"pagination":{"page":1,"limit":5}}'

call "GetProduct – found" \
    "proto.product.v1.ProductService" "GetProduct" \
    "{\"product_id\":\"${PRODUCT_ID}\"}"

call "GetProduct – not found" \
    "proto.product.v1.ProductService" "GetProduct" \
    '{"product_id":"00000000-0000-0000-0000-000000000000"}'

call "GetProduct – invalid id format" \
    "proto.product.v1.ProductService" "GetProduct" \
    '{"product_id":"invalid-uuid"}'

call "CreateProduct – success" \
    "proto.product.v1.ProductService" "CreateProduct" \
    '{"product":{"name":"Test Product","url":"test-product"},"user_id":"'"${USER_ID}"'"}'

call "CreateProduct – validation error (missing name)" \
    "proto.product.v1.ProductService" "CreateProduct" \
    '{"product":{"name":"","url":""},"user_id":"'"${USER_ID}"'"}'

call "CreateProduct – validation error (missing user_id)" \
    "proto.product.v1.ProductService" "CreateProduct" \
    '{"product":{"name":"No Actor Product","url":"no-actor-product"},"user_id":""}'

call "CreateProduct – validation error (duplicate url)" \
    "proto.product.v1.ProductService" "CreateProduct" \
    '{"product":{"name":"Dup URL Product","url":"iam"},"user_id":"'"${USER_ID}"'"}'

# Grab newly created product id for update/delete
NEW_PRODUCT_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.product.v1.ProductService/GetProducts 2>/dev/null \
  | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('name')=='Test Product']; print(p[0]['productId'] if p else '')" 2>/dev/null || true)

if [[ -n "${NEW_PRODUCT_ID}" ]]; then
    call "UpdateProduct – success" \
        "proto.product.v1.ProductService" "UpdateProduct" \
        '{"product":{"product_id":"'"${NEW_PRODUCT_ID}"'","name":"Test Product Updated","url":"test-product-updated"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteProduct – success" \
        "proto.product.v1.ProductService" "DeleteProduct" \
        '{"product_id":"'"${NEW_PRODUCT_ID}"'","user_id":"'"${USER_ID}"'"}'

    call "DeleteProduct – invalid id format" \
        "proto.product.v1.ProductService" "DeleteProduct" \
        '{"product_id":"invalid-uuid","user_id":"'"${USER_ID}"'"}'
else
    call "UpdateProduct – success" \
        "proto.product.v1.ProductService" "UpdateProduct" \
        '{"product":{"product_id":"'"${PRODUCT_ID}"'","name":"IAM Updated","url":"iam-updated"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteProduct – not found" \
        "proto.product.v1.ProductService" "DeleteProduct" \
        '{"product_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

    # restore
    grpcurl -plaintext -d '{"product":{"product_id":"'"${PRODUCT_ID}"'","name":"IAM","url":"iam"},"user_id":"'"${USER_ID}"'"}' \
        ${ADDR} proto.product.v1.ProductService/UpdateProduct > /dev/null 2>&1 || true
fi

call "UpdateProduct – validation error (missing product_id)" \
    "proto.product.v1.ProductService" "UpdateProduct" \
    '{"product":{"product_id":"","name":"Invalid Update","url":"invalid-update"},"user_id":"'"${USER_ID}"'"}'

call "UpdateProduct – invalid id format" \
    "proto.product.v1.ProductService" "UpdateProduct" \
    '{"product":{"product_id":"invalid-uuid","name":"Invalid UUID","url":"invalid-uuid"},"user_id":"'"${USER_ID}"'"}'

call "DeleteProduct – not found" \
    "proto.product.v1.ProductService" "DeleteProduct" \
    '{"product_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## ModuleService"

# ---- MODULE -----------------------------------------------
call "GetModules (page 1, limit 5)" \
    "proto.module.v1.ModuleService" "GetModules" \
    '{"pagination":{"page":1,"limit":5}}'

call "GetModule – found" \
    "proto.module.v1.ModuleService" "GetModule" \
    "{\"module_id\":\"${MODULE_ID}\"}"

call "GetModule – not found" \
    "proto.module.v1.ModuleService" "GetModule" \
    '{"module_id":"00000000-0000-0000-0000-000000000000"}'

call "GetModule – invalid id format" \
    "proto.module.v1.ModuleService" "GetModule" \
    '{"module_id":"invalid-uuid"}'

call "CreateModule – success" \
    "proto.module.v1.ModuleService" "CreateModule" \
    '{"module":{"name":"Test Module","product_id":"'"${PRODUCT_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "CreateModule – validation error (missing name)" \
    "proto.module.v1.ModuleService" "CreateModule" \
    '{"module":{"name":"","product_id":""},"user_id":"'"${USER_ID}"'"}'

call "CreateModule – validation error (invalid product_id format)" \
    "proto.module.v1.ModuleService" "CreateModule" \
    '{"module":{"name":"Invalid Product Ref","product_id":"invalid-uuid"},"user_id":"'"${USER_ID}"'"}'

NEW_MODULE_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.module.v1.ModuleService/GetModules 2>/dev/null \
  | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('name')=='Test Module']; print(p[0]['moduleId'] if p else '')" 2>/dev/null || true)

if [[ -n "${NEW_MODULE_ID}" ]]; then
    call "UpdateModule – success" \
        "proto.module.v1.ModuleService" "UpdateModule" \
        '{"module":{"module_id":"'"${NEW_MODULE_ID}"'","name":"Test Module Updated","product_id":"'"${PRODUCT_ID}"'"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteModule – success" \
        "proto.module.v1.ModuleService" "DeleteModule" \
        '{"module_id":"'"${NEW_MODULE_ID}"'","user_id":"'"${USER_ID}"'"}'

    call "DeleteModule – invalid id format" \
        "proto.module.v1.ModuleService" "DeleteModule" \
        '{"module_id":"invalid-uuid","user_id":"'"${USER_ID}"'"}'
else
    call "UpdateModule – success" \
        "proto.module.v1.ModuleService" "UpdateModule" \
        '{"module":{"module_id":"'"${MODULE_ID}"'","name":"module 1 updated","product_id":"'"${PRODUCT_ID}"'"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteModule – not found" \
        "proto.module.v1.ModuleService" "DeleteModule" \
        '{"module_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'
fi

call "UpdateModule – validation error (missing module_id)" \
    "proto.module.v1.ModuleService" "UpdateModule" \
    '{"module":{"module_id":"","name":"Invalid Module","product_id":"'"${PRODUCT_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "UpdateModule – invalid id format" \
    "proto.module.v1.ModuleService" "UpdateModule" \
    '{"module":{"module_id":"invalid-uuid","name":"Invalid UUID","product_id":"'"${PRODUCT_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "DeleteModule – not found" \
    "proto.module.v1.ModuleService" "DeleteModule" \
    '{"module_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## ActionService"

# ---- ACTION -----------------------------------------------
call "GetActions (page 1, limit 10)" \
    "proto.action.v1.ActionService" "GetActions" \
    '{"pagination":{"page":1,"limit":10}}'

call "GetAction – not found" \
    "proto.action.v1.ActionService" "GetAction" \
    '{"action_id":"00000000-0000-0000-0000-000000000000"}'

call "GetAction – invalid id format" \
    "proto.action.v1.ActionService" "GetAction" \
    '{"action_id":"invalid-uuid"}'

call "CreateAction – success" \
    "proto.action.v1.ActionService" "CreateAction" \
    '{"action":{"name":"read","method":"GET","description":"Read action","resource_id":"'"${SETUP_RESOURCE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "CreateAction – validation error (missing name)" \
    "proto.action.v1.ActionService" "CreateAction" \
    '{"action":{"name":"","method":"","resource_id":""},"user_id":"'"${USER_ID}"'"}'

call "CreateAction – validation error (invalid resource_id format)" \
    "proto.action.v1.ActionService" "CreateAction" \
    '{"action":{"name":"read-invalid","method":"GET","resource_id":"invalid-uuid"},"user_id":"'"${USER_ID}"'"}'

NEW_ACTION_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.action.v1.ActionService/GetActions 2>/dev/null \
    | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('name')=='read']; print(p[0].get('actionId','') if p else '')" 2>/dev/null || true)
if [[ -z "${NEW_ACTION_ID}" ]]; then
        NEW_ACTION_ID=$(psql -U postgres -d go_api -t -c "SELECT action_id FROM actions WHERE name='read' LIMIT 1;" 2>/dev/null | tr -d ' \n' || true)
fi

if [[ -n "${NEW_ACTION_ID}" ]]; then
    call "GetAction – found" \
        "proto.action.v1.ActionService" "GetAction" \
        "{\"action_id\":\"${NEW_ACTION_ID}\"}"

    call "UpdateAction – success" \
        "proto.action.v1.ActionService" "UpdateAction" \
        '{"action":{"action_id":"'"${NEW_ACTION_ID}"'","name":"read updated","method":"GET","description":"Updated read action"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteAction – success" \
        "proto.action.v1.ActionService" "DeleteAction" \
        '{"action_id":"'"${NEW_ACTION_ID}"'","user_id":"'"${USER_ID}"'"}'
fi

call "UpdateAction – validation error (missing action_id)" \
    "proto.action.v1.ActionService" "UpdateAction" \
    '{"action":{"action_id":"","name":"x","method":"GET","resource_id":"'"${SETUP_RESOURCE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "UpdateAction – not found" \
    "proto.action.v1.ActionService" "UpdateAction" \
    '{"action":{"action_id":"00000000-0000-0000-0000-000000000000","name":"x","method":"GET","resource_id":"'"${SETUP_RESOURCE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "DeleteAction – not found" \
    "proto.action.v1.ActionService" "DeleteAction" \
    '{"action_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## ResourceService"

# ---- RESOURCE -----------------------------------------------
call "GetResources (page 1, limit 10)" \
    "proto.resource.v1.ResourceService" "GetResources" \
    '{"pagination":{"page":1,"limit":10}}'

call "GetResource – not found" \
    "proto.resource.v1.ResourceService" "GetResource" \
    '{"resource_id":"00000000-0000-0000-0000-000000000000"}'

call "GetResource – invalid id format" \
    "proto.resource.v1.ResourceService" "GetResource" \
    '{"resource_id":"invalid-uuid"}'

call "CreateResource – success" \
    "proto.resource.v1.ResourceService" "CreateResource" \
    '{"resource":{"name":"users-api","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "CreateResource – validation error (missing name)" \
    "proto.resource.v1.ResourceService" "CreateResource" \
    '{"resource":{"name":"","module_id":""},"user_id":"'"${USER_ID}"'"}'

call "CreateResource – validation error (invalid module_id format)" \
    "proto.resource.v1.ResourceService" "CreateResource" \
    '{"resource":{"name":"invalid-resource","module_id":"invalid-uuid"},"user_id":"'"${USER_ID}"'"}'

NEW_RESOURCE_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.resource.v1.ResourceService/GetResources 2>/dev/null \
    | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('name')=='users-api']; print(p[0].get('resourceId','') if p else '')" 2>/dev/null || true)
if [[ -z "${NEW_RESOURCE_ID}" ]]; then
        NEW_RESOURCE_ID=$(psql -U postgres -d go_api -t -c "SELECT resource_id FROM resources WHERE name='users-api' LIMIT 1;" 2>/dev/null | tr -d ' \n' || true)
fi

if [[ -n "${NEW_RESOURCE_ID}" ]]; then
    call "GetResource – found" \
        "proto.resource.v1.ResourceService" "GetResource" \
        "{\"resource_id\":\"${NEW_RESOURCE_ID}\"}"

    call "UpdateResource – success" \
        "proto.resource.v1.ResourceService" "UpdateResource" \
        '{"resource":{"resource_id":"'"${NEW_RESOURCE_ID}"'","name":"users-api-updated","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteResource – success" \
        "proto.resource.v1.ResourceService" "DeleteResource" \
        '{"resource_id":"'"${NEW_RESOURCE_ID}"'","user_id":"'"${USER_ID}"'"}'
fi

call "UpdateResource – validation error (missing resource_id)" \
    "proto.resource.v1.ResourceService" "UpdateResource" \
    '{"resource":{"resource_id":"","name":"x","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "UpdateResource – not found" \
    "proto.resource.v1.ResourceService" "UpdateResource" \
    '{"resource":{"resource_id":"00000000-0000-0000-0000-000000000000","name":"ghost","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "DeleteResource – not found" \
    "proto.resource.v1.ResourceService" "DeleteResource" \
    '{"resource_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## UserService"

# ---- USER -----------------------------------------------
call "GetUsers (page 1, limit 5)" \
    "proto.user.v1.UserService" "GetUsers" \
    '{"pagination":{"page":1,"limit":5}}'

call "GetUser – found" \
    "proto.user.v1.UserService" "GetUser" \
    "{\"user_id\":\"${USER_ID}\"}"

call "GetUser – not found" \
    "proto.user.v1.UserService" "GetUser" \
    '{"user_id":"00000000-0000-0000-0000-000000000000"}'

call "GetUser – invalid id format" \
    "proto.user.v1.UserService" "GetUser" \
    '{"user_id":"invalid-uuid"}'

call "CreateUser – success" \
    "proto.user.v1.UserService" "CreateUser" \
    '{"user":{"username":"testuser","email":"testuser@example.com","password":"Test@1234","phone":"+84901234999"},"user_id":"'"${USER_ID}"'"}'

call "CreateUser – validation error (duplicate email)" \
    "proto.user.v1.UserService" "CreateUser" \
    '{"user":{"username":"manhlam2","email":"lamquangmanh@gmail.com","password":"Test@1234"},"user_id":"'"${USER_ID}"'"}'

call "CreateUser – validation error (invalid username format)" \
    "proto.user.v1.UserService" "CreateUser" \
    '{"user":{"username":"x","email":"newuser@example.com","password":"Test@1234"},"user_id":"'"${USER_ID}"'"}'

call "CreateUser – validation error (missing fields)" \
    "proto.user.v1.UserService" "CreateUser" \
    '{"user":{"username":"","email":"","password":""},"user_id":"'"${USER_ID}"'"}'

call "CreateUser – validation error (invalid email format)" \
    "proto.user.v1.UserService" "CreateUser" \
    '{"user":{"username":"invalid_email_user","email":"not-an-email","password":"Test@1234"},"user_id":"'"${USER_ID}"'"}'

NEW_USER_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.user.v1.UserService/GetUsers 2>/dev/null \
  | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('email')=='testuser@example.com']; print(p[0]['userId'] if p else '')" 2>/dev/null || true)

if [[ -n "${NEW_USER_ID}" ]]; then
    call "UpdateUser – success" \
        "proto.user.v1.UserService" "UpdateUser" \
        '{"user":{"user_id":"'"${NEW_USER_ID}"'","username":"testuser_updated","email":"testuser_updated@example.com","phone":"+84901234998"},"user_id":"'"${USER_ID}"'"}'

    call "ChangePassword – success" \
        "proto.user.v1.UserService" "ChangePassword" \
        '{"user_id":"'"${NEW_USER_ID}"'","password":"NewPass@5678"}'

    call "DeleteUser – success" \
        "proto.user.v1.UserService" "DeleteUser" \
        '{"user_id":"'"${NEW_USER_ID}"'","deleted_user_id":"'"${USER_ID}"'"}'
else
    call "UpdateUser – not found" \
        "proto.user.v1.UserService" "UpdateUser" \
        '{"user":{"user_id":"00000000-0000-0000-0000-000000000000","username":"ghost"},"user_id":"'"${USER_ID}"'"}'

    call "ChangePassword – success" \
        "proto.user.v1.UserService" "ChangePassword" \
        '{"user_id":"'"${USER_ID}"'","password":"Admin@1234"}'

    call "DeleteUser – not found" \
        "proto.user.v1.UserService" "DeleteUser" \
        '{"user_id":"00000000-0000-0000-0000-000000000000","deleted_user_id":"'"${USER_ID}"'"}'
fi

call "UpdateUser – validation error (missing user_id)" \
    "proto.user.v1.UserService" "UpdateUser" \
    '{"user":{"user_id":"","username":"x"},"user_id":"'"${USER_ID}"'"}'

call "ChangePassword – validation error (missing password)" \
    "proto.user.v1.UserService" "ChangePassword" \
    '{"user_id":"'"${USER_ID}"'","password":""}'

call "DeleteUser – invalid id format" \
    "proto.user.v1.UserService" "DeleteUser" \
    '{"user_id":"invalid-uuid","deleted_user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## RoleService"

# ---- ROLE -----------------------------------------------
call "GetRoles (page 1, limit 5)" \
    "proto.role.v1.RoleService" "GetRoles" \
    '{"pagination":{"page":1,"limit":5}}'

call "GetRole – not found" \
    "proto.role.v1.RoleService" "GetRole" \
    '{"role_id":"00000000-0000-0000-0000-000000000000"}'

call "GetRole – invalid id format" \
    "proto.role.v1.RoleService" "GetRole" \
    '{"role_id":"invalid-uuid"}'

call "CreateRole – success" \
    "proto.role.v1.RoleService" "CreateRole" \
    '{"role":{"name":"admin","description":"Administrator role","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "CreateRole – validation error (missing name)" \
    "proto.role.v1.RoleService" "CreateRole" \
    '{"role":{"name":""},"user_id":"'"${USER_ID}"'"}'

call "CreateRole – validation error (invalid module_id format)" \
    "proto.role.v1.RoleService" "CreateRole" \
    '{"role":{"name":"invalid-role-module","module_id":"invalid-uuid"},"user_id":"'"${USER_ID}"'"}'

NEW_ROLE_ID=$(grpcurl -plaintext -d '{"pagination":{"page":1,"limit":50}}' ${ADDR} proto.role.v1.RoleService/GetRoles 2>/dev/null \
    | python3 -c "import sys,json; data=json.load(sys.stdin); items=data.get('data',[]); p=[x for x in items if x.get('name')=='admin']; print(p[0].get('roleId','') if p else '')" 2>/dev/null || true)
if [[ -z "${NEW_ROLE_ID}" ]]; then
        NEW_ROLE_ID=$(psql -U postgres -d go_api -t -c "SELECT role_id FROM roles WHERE name='admin' LIMIT 1;" 2>/dev/null | tr -d ' \n' || true)
fi

if [[ -n "${NEW_ROLE_ID}" ]]; then
    call "GetRole – found" \
        "proto.role.v1.RoleService" "GetRole" \
        "{\"role_id\":\"${NEW_ROLE_ID}\"}"

    call "UpdateRole – success" \
        "proto.role.v1.RoleService" "UpdateRole" \
        '{"role":{"role_id":"'"${NEW_ROLE_ID}"'","name":"admin updated","description":"Updated admin role"},"user_id":"'"${USER_ID}"'"}'

    call "DeleteRole – success" \
        "proto.role.v1.RoleService" "DeleteRole" \
        '{"role_id":"'"${NEW_ROLE_ID}"'","user_id":"'"${USER_ID}"'"}'
fi

call "UpdateRole – validation error (missing role_id)" \
    "proto.role.v1.RoleService" "UpdateRole" \
    '{"role":{"role_id":"","name":"x","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "UpdateRole – not found" \
    "proto.role.v1.RoleService" "UpdateRole" \
    '{"role":{"role_id":"00000000-0000-0000-0000-000000000000","name":"ghost-role","module_id":"'"${MODULE_ID}"'"},"user_id":"'"${USER_ID}"'"}'

call "DeleteRole – not found" \
    "proto.role.v1.RoleService" "DeleteRole" \
    '{"role_id":"00000000-0000-0000-0000-000000000000","user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "## AuthService"

# ---- AUTH -----------------------------------------------
call "Login – success" \
    "proto.auth.v1.AuthService" "Login" \
    '{"username":"manhlam","password":"Admin@1234"}'

call "Login – invalid credentials" \
    "proto.auth.v1.AuthService" "Login" \
    '{"username":"manhlam","password":"wrongpassword"}'

call "Login – missing fields" \
    "proto.auth.v1.AuthService" "Login" \
    '{"username":"","password":""}'

call "GetMe – stub" \
    "proto.auth.v1.AuthService" "GetMe" \
    '{"token":"sample-token"}'

call "Verify – stub" \
    "proto.auth.v1.AuthService" "Verify" \
    '{"token":"sample-token"}'

echo ""
echo "---"
echo ""
echo "## MenuService"

# ---- MENU -----------------------------------------------
call_empty "GetSuperMenus" \
    "proto.menu.v1.MenuService" "GetSuperMenus"

echo ""
echo "---"
echo ""
echo "## PermissionService"

# ---- PERMISSION -----------------------------------------------
call "GetPermissions" \
    "proto.permission.v1.PermissionService" "GetPermissions" \
    '{"pagination":{"page":1,"limit":10}}'

call "GetPermission – not found (stub)" \
    "proto.permission.v1.PermissionService" "GetPermission" \
    '{"permission_id":"00000000-0000-0000-0000-000000000000"}'

call "CreatePermission – stub" \
    "proto.permission.v1.PermissionService" "CreatePermission" \
    '{"permission":{"role_id":"00000000-0000-0000-0000-000000000001","resource_id":"00000000-0000-0000-0000-000000000002","action_ids":["00000000-0000-0000-0000-000000000003"]},"user_id":"'"${USER_ID}"'"}'

call "GetPermissionsByUserId – stub" \
    "proto.permission.v1.PermissionService" "GetPermissionsByUserId" \
    '{"user_id":"'"${USER_ID}"'"}'

echo ""
echo "---"
echo ""
echo "*End of API test results.*"

} > "${OUT}"

echo "✅  Done. Results written to ${OUT}"
