apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  # namespace: default
data:
  # This key must match Deployment volume.items[].key and volumeMount subPath.
  config.yml: |
    grpc:
      port: 50051

    http:
      port: 8080

    database:
      host: postgres.default.svc.cluster.local
      port: 5432
      user: go_api_user
      password: go_api_password
      name: go_api
      ssl_mode: disable

    logger:
      level: info
      format: json
