// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: go-api/proto/common/v1/pagination.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaginationRequest carries offset-based pagination input.
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_go_api_proto_common_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_proto_common_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_go_api_proto_common_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// PaginationResponse carries pagination metadata in list responses.
type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_go_api_proto_common_v1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_proto_common_v1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_go_api_proto_common_v1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_go_api_proto_common_v1_pagination_proto protoreflect.FileDescriptor

const file_go_api_proto_common_v1_pagination_proto_rawDesc = "" +
	"\n" +
	"'go-api/proto/common/v1/pagination.proto\x12\tcommon.v1\"A\n" +
	"\x11PaginationRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"X\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05totalB\"Z go-api/pkg/api/commonpb;commonpbb\x06proto3"

var (
	file_go_api_proto_common_v1_pagination_proto_rawDescOnce sync.Once
	file_go_api_proto_common_v1_pagination_proto_rawDescData []byte
)

func file_go_api_proto_common_v1_pagination_proto_rawDescGZIP() []byte {
	file_go_api_proto_common_v1_pagination_proto_rawDescOnce.Do(func() {
		file_go_api_proto_common_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_api_proto_common_v1_pagination_proto_rawDesc), len(file_go_api_proto_common_v1_pagination_proto_rawDesc)))
	})
	return file_go_api_proto_common_v1_pagination_proto_rawDescData
}

var file_go_api_proto_common_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_api_proto_common_v1_pagination_proto_goTypes = []any{
	(*PaginationRequest)(nil),  // 0: common.v1.PaginationRequest
	(*PaginationResponse)(nil), // 1: common.v1.PaginationResponse
}
var file_go_api_proto_common_v1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_api_proto_common_v1_pagination_proto_init() }
func file_go_api_proto_common_v1_pagination_proto_init() {
	if File_go_api_proto_common_v1_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_api_proto_common_v1_pagination_proto_rawDesc), len(file_go_api_proto_common_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_api_proto_common_v1_pagination_proto_goTypes,
		DependencyIndexes: file_go_api_proto_common_v1_pagination_proto_depIdxs,
		MessageInfos:      file_go_api_proto_common_v1_pagination_proto_msgTypes,
	}.Build()
	File_go_api_proto_common_v1_pagination_proto = out.File
	file_go_api_proto_common_v1_pagination_proto_goTypes = nil
	file_go_api_proto_common_v1_pagination_proto_depIdxs = nil
}
